### ISSUE TITLE
Need Seperate examples for using dummy.js in different ways

### ISSUE THREAD

**Issue by spyshiv** [spyshiv/dummyjs#1]
Right now only one file (example/index.html) having usage of generating paragraphs, sentences and words. I need three separate files for better documentation. :smiley: 

To do
- [ ] example.html for generating dummy paragraphs
- [ ] example.html for generating dummy sentences
- [ ] example.html for generating dummy words

Please follow documentation (README.md) to know how to use dummy.js

Make sure your code should be well formatted either it's html or css.

**Comment by abhyudaypratap** [comment]
i am taking up the task

**Comment by spyshiv** [comment]
@abhyudaypratap : Nice to have you on board. :+1:
