### ISSUE TITLE
Need some Animation in examples 

### ISSUE THREAD

**Issue by spyshiv** [spyshiv/dummyjs#4]
Need animation using jquery or JavaScript which can display how dummy data is creating.like letter typing.

**Comment by Ne3l** [comment]
Can i take this one?

**Comment by spyshiv** [comment]
Yeah sure  @Ne3l 👍

**Comment by ghost** [comment]
is it still open ?

**Comment by spyshiv** [comment]
@talent404 : Yes, it is.

**Comment by ghost** [comment]
What sort of animation ? Like the text appearing dynamically as it is being generated?

**Comment by spyshiv** [comment]
Yes. Some sort of. I want to add that as an option. If anyone want to use that animation in generating dummy data, a simple attribute `dummy-animation = "True"` can trigger that.
